# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b697ef5b8e1e56bf5f111ceb56c64408e6e08b14ef54e5bf1891cbd83e923c2d145d9d1f8f99640e9ac061a2901c4086bc8b6d254720e0fe7c133b73c1d4ccf

test:
  secret_key_base: cfd4a87bec886bb57cdbc28f72f3843c1c1ad4e4ac278c576d94e3eef082122565aaa7503ec6d8136243ddea5a52e30eb0e3cbf022cf88c1d0343b21e7970b2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
